skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "9zEKwVUB5iWrzw8St3cd6tyz4FS64JaaJt3cShXaT1W7"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
