name: Deploy Web App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install day4 dependencies
        run: pnpm --filter day4 install
        # - run: pnpm install
        #     working-directory: folder1/folder2

      - name: Build day4 app
        run: pnpm --filter day4 build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: week1/day4/dist
          destination_dir: week1/day4